# Generated by Django 5.1.7 on 2025-03-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_investment_shares_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='shares_purchased',
        ),
    ]
