# Generated by Django 5.1.7 on 2025-03-25 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0014_remove_initiative_technology_type_and_more'),
        ('investments', '0006_investmentgoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='carbon_reduced',
            new_name='carbon_impact',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='energy_saved',
            new_name='energy_impact',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='water_conserved',
            new_name='water_impact',
        ),
        migrations.AddField(
            model_name='investment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='investment',
            name='initiative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='initiatives.initiative'),
            preserve_default=False,
        ),
    ]
