# Generated by Django (update the version)
from django.db import migrations
from investments.impact_calculator import ImpactCalculator

def recalculate_impacts(apps, schema_editor):
    Investment = apps.get_model('investments', 'Investment')
    Initiative = apps.get_model('initiatives', 'Initiative')
    
    # Initialize calculator once
    impact_calculator = ImpactCalculator()
    
    # Process in batches to avoid memory issues
    batch_size = 1000
    investments = Investment.objects.all().select_related('initiative')
    
    for i in range(0, investments.count(), batch_size):
        batch = investments[i:i+batch_size]
        for investment in batch:
            try:
                # Get category names
                categories = investment.initiative.categories.all()
                category_names = [cat.name for cat in categories]
                
                # Calculate new impact values
                carbon, energy, water = impact_calculator.predict_impact(
                    investment_amount=float(investment.amount),
                    category_names=category_names,
                    project_duration_months=investment.initiative.duration_months,
                    project_scale=investment.initiative.project_scale,
                    location=investment.initiative.location,
                    technology_type=investment.initiative.technology_type
                )
                
                # Update fields
                investment.carbon_impact = carbon
                investment.energy_impact = energy
                investment.water_impact = water
                investment.save(update_fields=[
                    'carbon_impact', 
                    'energy_impact', 
                    'water_impact'
                ])
                
            except Exception as e:
                print(f"Failed to update investment {investment.id}: {str(e)}")
                continue

class Migration(migrations.Migration):
    dependencies = [
        ('investments', '0007_rename_carbon_reduced_investment_carbon_impact_and_more'),
    ]

    operations = [
        migrations.RunPython(recalculate_impacts),
    ]