# Generated by Django 5.1.7 on 2025-03-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='duration_months',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
