# Generated by Django 5.1.7 on 2025-03-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0004_initiative_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='project_scale',
            field=models.PositiveIntegerField(default=1, help_text='Scale of project (1=small, 5=medium, 10=large)'),
        ),
    ]
