# Generated by Django 5.1.7 on 2025-03-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_initiative_project_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='location',
            field=models.CharField(choices=[('North India', 'North India'), ('South India', 'South India'), ('East India', 'East India'), ('West India', 'West India')], default='North India', max_length=50),
        ),
        migrations.AddField(
            model_name='initiative',
            name='technology_type',
            field=models.CharField(choices=[('Solar', 'Solar'), ('Wind', 'Wind'), ('Hydro', 'Hydro'), ('Organic', 'Organic'), ('Mechanical', 'Mechanical'), ('Chemical', 'Chemical'), ('Biofuel', 'Biofuel'), ('EV', 'Electric Vehicle'), ('Manual', 'Manual'), ('AI', 'Artificial Intelligence')], default='Manual', max_length=50),
        ),
    ]
