# Generated by Django 5.1.7 on 2025-03-23 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_initiative_location_initiative_technology_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_funding', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('duration_months', models.PositiveIntegerField(default=12)),
                ('company_scale', models.PositiveIntegerField(default=1, help_text='Scale of company (1=startup, 5=mid-size, 10=large)')),
                ('location', models.CharField(choices=[('North India', 'North India'), ('South India', 'South India'), ('East India', 'East India'), ('West India', 'West India')], default='North India', max_length=50)),
                ('technology_type', models.CharField(choices=[('Solar', 'Solar'), ('Wind', 'Wind'), ('Hydro', 'Hydro'), ('Organic', 'Organic'), ('Mechanical', 'Mechanical'), ('Chemical', 'Chemical'), ('Biofuel', 'Biofuel'), ('EV', 'Electric Vehicle'), ('Manual', 'Manual'), ('AI', 'Artificial Intelligence')], default='Manual', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('funded', 'Funded'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='initiatives.category')),
            ],
        ),
    ]
