# Generated by Django 5.1.7 on 2025-03-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0007_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='current_funding',
        ),
        migrations.RemoveField(
            model_name='company',
            name='funding_goal',
        ),
        migrations.AddField(
            model_name='company',
            name='share_price',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Price per share in ₹', max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='shares_sold',
            field=models.PositiveIntegerField(default=0, help_text='Number of shares purchased'),
        ),
        migrations.AddField(
            model_name='company',
            name='total_shares',
            field=models.PositiveIntegerField(default=1000, help_text='Total shares available for purchase'),
        ),
    ]
