# Generated by Django 5.1.7 on 2025-03-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0008_remove_company_current_funding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='category',
        ),
        migrations.AddField(
            model_name='company',
            name='categories',
            field=models.ManyToManyField(related_name='companies', to='initiatives.category'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='categories',
            field=models.ManyToManyField(related_name='initiatives', to='initiatives.category'),
        ),
    ]
