# Generated by Django 5.1.7 on 2025-03-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0009_remove_company_category_remove_initiative_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='technology_type',
        ),
    ]
