# Generated by Django 5.1.7 on 2025-03-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0011_alter_category_name'),
        ('investments', '0005_remove_investment_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
