# Generated by Django 5.1.7 on 2025-03-25 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0012_delete_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initiative',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='initiative',
            name='carbon_impact',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='initiative',
            name='energy_impact',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='initiative',
            name='water_impact',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='duration_months',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='project_scale',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='technology_type',
            field=models.CharField(max_length=100),
        ),
    ]
