# Generated by Django 5.1.7 on 2025-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0013_alter_initiative_options_initiative_carbon_impact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='technology_type',
        ),
        migrations.AddField(
            model_name='initiative',
            name='carbon_reduction_per_investment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='initiative',
            name='energy_savings_per_investment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='initiative',
            name='max_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='min_investment',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name='initiative',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='initiative',
            name='roi_estimate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='initiative',
            name='water_savings_per_investment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='carbon_impact',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='duration_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='energy_impact',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='project_scale',
            field=models.IntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'Very Large'), (5, 'Enterprise')], default=3),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='water_impact',
            field=models.FloatField(default=0),
        ),
    ]
