# Generated by Django 5.1.7 on 2025-03-27 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initiatives', '0016_alter_initiative_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_completed', models.BooleanField(default=False)),
                ('interests_completed', models.BooleanField(default=False)),
                ('investment_profile_completed', models.BooleanField(default=False)),
                ('tutorial_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_tolerance', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], default='moderate', max_length=10)),
                ('investment_timeframe', models.CharField(choices=[('short', 'Short-term (< 1 year)'), ('medium', 'Medium-term (1-5 years)'), ('long', 'Long-term (5+ years)')], default='medium', max_length=10)),
                ('min_investment', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('max_investment', models.DecimalField(decimal_places=2, default=500000.0, max_digits=12)),
                ('carbon_priority', models.IntegerField(default=5)),
                ('water_priority', models.IntegerField(default=5)),
                ('energy_priority', models.IntegerField(default=5)),
                ('interested_categories', models.ManyToManyField(related_name='interested_users', to='initiatives.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
